modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mcxrplay"
version = "${version}"
displayName = "MCXR Play"
authors = "Sorenon, TheJudge, CADIndie, IzzyDotExe, Flamgop"
description = '''
VR!
'''
logoFile = "logo.png"

[[dependencies.mcxrplay]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcxrplay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcxrplay]]
modId = "architectury"
mandatory = true
versionRange = "[5.7.27,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mcxrplay]]
modId = "mcxrcore"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"